apiVersion: apps/v1
kind: Deployment
metadata:
  name: golinks
  namespace: default
spec:
  selector:
    matchLabels:
      app: golinks
  template:
    metadata:
      labels:
        app: golinks
    spec:
      volumes:
        - name: golinks-data
          persistentVolumeClaim:
            claimName: golinks-data
      containers:
        - name: golinks
          image: ghcr.io/tailscale/golink:main
          imagePullPolicy: Always
          volumeMounts:
            - name: golinks-data
              mountPath: /home/nonroot
          env:
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tsauthkey
                  key: tsauthkey
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
