---
apiVersion: v1
kind: Service
metadata:
  name: golinks
  namespace: default
spec:
  selector:
    app: golinks
  ports:
    - name: golinks
      port: 80
      targetPort: http
      protocol: TCP
  type: ClusterIP
---

