resources:
  - grafana-admin-sealed.yaml
  - home-assistant-token-sealed.yaml
  - mqtt-credentials-sealed.yaml
  - mqtt-passwd-sealed.yaml
  - playnite-web-credentials-sealed.yaml
  - playnite-web-db-credentials-sealed.yaml
  - psn-accounts-sealed.yaml
  - regcred-sealed.yaml
  - tsauthkey-sealed.yaml
  - tunnel-credentials-sealed.yaml
  - unifi-sealed.yaml
  - homebox-oidc-sealed.yaml