apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - volumes.yaml
  - piper-deployment.yaml
  - piper-service.yaml
  - whisper-deployment.yaml
  - whisper-service.yaml
