apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper
  namespace: default
spec:
  selector:
    matchLabels:
      app: whisper
  template:
    metadata:
      labels:
        app: whisper
    spec:
      serviceAccountName: app
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        gpu: "true"
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      volumes:
        - name: whisper-data
          persistentVolumeClaim:
            claimName: whisper-data-pvc
      containers:
        - name: whisper
          image: ghcr.io/andrew-codes/whisper:latest
          imagePullPolicy: Always
          args:
            [
              "--model",
              "base.en",
              "--language",
              "en",
              "--compute-type",
              "float16",
              "--device",
              "cuda",
            ]
          env:
            - name: TZ
              value: America/New_York
          ports:
            - name: whisper
              containerPort: 10300
              protocol: TCP
          resources:
            requests:
              nvidia.com/gpu: "2"
            limits:
              nvidia.com/gpu: "2"
          volumeMounts:
            - name: whisper-data
              mountPath: /data
