---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-version-control
  namespace: default
spec:
  ports:
    - name: http
      protocol: TCP
      port: 54001
      targetPort: http
  selector:
    name: home-assistant-version-control
  type: ClusterIP
